version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    container_name: elasticsearch2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Limit memory usage
    ports:
      - "9200:9200"
    volumes:
      - /c/Users/Ibukun/Desktop/goProxy/observability:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash
    volumes:
      - ./udp.conf:/usr/share/logstash/pipeline/udp.conf
    ports:
      - "7777:7777/udp"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch2:9200
    depends_on:
      - elasticsearch
